version: "3.8"

services:
  pgsql:
    image: postgres:13.1
    restart: always
    volumes:
      - node_pg_data:/var/lib/postgresql/data
    networks:
      - node_pg_network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dockerdev
      POSTGRES_PASSWORD: dockerdev


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - node_pgadmin_data:/var/lib/pgadmin
    networks:
      - node_pg_network
    ports:
      - 4444:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.org
      PGADMIN_DEFAULT_PASSWORD: dockerdev

volumes:
  node_pg_data:
  node_pgadmin_data:

networks:
  node_pg_network:
